@echo off
REM Quick start script for Rock Paper Scissors Game (Windows)
echo 🎮 Starting Rock Paper Scissors Game...
echo 📦 Compiling project...
mvn compile
echo 🚀 Running game...
mvn exec:java -Dexec.mainClass="ui.MainWindow"
pause
